language: php
php:
    - 7.0
addons:
    postgresql: "9.5"

before_script:
    - travis_retry composer self-update --no-interaction
    - travis_retry composer update --no-interaction --prefer-dist

    - composer dump-autoload --classmap-authoritative

script: ./tests/run.sh -s $NTESTER_FLAGS ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
